# Generated by Django 3.2.12 on 2022-03-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
