# Generated by Django 3.2.12 on 2022-03-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
