# Generated by Django 3.2.12 on 2022-03-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
