# Generated by Django 3.2.12 on 2022-03-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20220329_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
