# Generated by Django 3.2.12 on 2022-03-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_delete_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
